services:
  - type: web
    name: signature-extractor
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn signature_extractor.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
